In [27]:
import numpy as np

arr = np.arange(2,1000,10)
print(arr)

arr2 = np.ones((2,4,3))#zeros , full de var np.full((3,3),19) 19 lardan oluian 3 3 matris

#arr3 = np.linspace((2,4,3))

arr43 = np.linspace(2,4,5)#başlangıç ve bitiş belirle o aralığı 5 eşit parçaya böler


arr8=np.full((3,3),5)
arr8=np.empty((3,3))

arrr = np.array([7,8,9,10],dtype=np.int32) #32bitlik alan ayır diyoruz. Hız için
arrr = np.array([7,8,9,10],dtype="i") #(integer) i veya i4 32bit, i8 64 bit demek. aynısının f4 ve f8 de float için geçerli 
#unsigned integer u1 ve u2 var u18 bittir. (pozitif integer ve 0)
arrss = np.array([b"aa",b"cc",b"dd"],dtype="S")
arrss = np.array(["aa","cc","dd"],dtype="U")
 #başına b gelirse asciye göre tutar. yoksa uniqostringtir (yeni)
#s ise asci string için, s5 gibi sayı eklersen en fazla 5 karakterli string tutar
#b ise bool true or false
#c8 ve c 16 ise complex number


#object alayını ortak tutar
#aray=np.array(11,8.5,"aaa",'a',[1,3,4],dtype="object")

#M8[D] tarih , m8[h] saat
#arayy=np.array("2005-07-21","2003-07-21", dtype="M8[D]")

arrs = np.array([3.3,4.4,5.5])
arrs2 = arrs.astype(str)#stringe döndürdü 

oldArr=np.array([1,2,3,4])
new1arr=oldArr.copy() #değiştirmez 
new2arr=oldArr.view()  #değiştirir 
oldArr[0]=10

print(new1arr.base)#None
print(new2arr.base) #[10  2  3  4] orjinalini getirir

#oldArr.shape  bu kaç bouytlu olduğunu verir
#sewarr=oldArr.reshape(4,3) 4 e 3 lük bir matrise çevirmöen gerekiyor !!!!!!!!!!!!!!!!!
#not eğer 3 boyutlu gibi bir dönüşüm istiyorsal ve sonda kaç tane olduğunu numpy hesaplayacaksa sonuncunun parametre -1 yazılır
#flatten ise çok buyutlu bir arryi tek boyuta indirger
#ravel ise yine tek boyut ayapar ama view ile orjinalinin görünümünü verir


[  2  12  22  32  42  52  62  72  82  92 102 112 122 132 142 152 162 172
 182 192 202 212 222 232 242 252 262 272 282 292 302 312 322 332 342 352
 362 372 382 392 402 412 422 432 442 452 462 472 482 492 502 512 522 532
 542 552 562 572 582 592 602 612 622 632 642 652 662 672 682 692 702 712
 722 732 742 752 762 772 782 792 802 812 822 832 842 852 862 872 882 892
 902 912 922 932 942 952 962 972 982 992]
None
[10  2  3  4]


In [15]:
import time

time1=time.time()
list=[]
for a in range(1_000_000):
    power1=a**100
    list.append(power1)
    
z1=time.time()
print(z1-time1)

0.8326835632324219


In [18]:

import numpy as np
time2=time.time()
list2=[]
list2 = np.arange(1_000_000)**100
 
    
z2=time.time()
print(z2-time2)

0.004519462585449219


In [4]:
import numpy as np
oldArr = np.array([[[1,2,3,],[12,12,34]],[[1,2,3,],[12,12,34]]])
oldArr.shape #boyutunu verir parametre sayısı
#oldArr.ndim   #boyutunu verir 3 boyurtlu gibi

(2, 2, 3)

In [47]:
np.random.randint(2,10,(4,4)) # 2den 10 a kadar rasgele sayı getirir


array([[7, 7, 6, 2],
       [3, 4, 2, 5],
       [4, 7, 5, 2],
       [2, 9, 6, 5]], dtype=int32)

In [53]:
million = np.arange(5,1000000,100)
print(million)

[     5    105    205 ... 999705 999805 999905]


In [9]:
import numpy as np
x=np.eye(8,k=5)
print(x)

[[0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
np.identity(5) #köşegenleri 1 olan 5 'e 5li bir matris.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.diag([1,2,3,2,1])#np.diag(x) burada x matrisinin köşegenini verir

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [7]:
import numpy as np
arrrr = np.array([[[1,2,3,],[12,12,34]],[[1,2,3,],[12,12,34]]])
arrrr>5

array([[[False, False, False],
        [ True,  True,  True]],

       [[False, False, False],
        [ True,  True,  True]]])

In [10]:
arrrr[arrrr>5]

array([12, 12, 34, 12, 12, 34])

In [5]:
arrrr[arrrr==5]

NameError: name 'arrrr' is not defined

In [14]:
arrrr[arrrr==5].size

0

In [19]:
sifir=arrrr%2==0
arrrr[sifir]

array([ 2, 12, 12, 34,  2, 12, 12, 34])

In [32]:
ary= np.array([[[1,2,3,],[132,222,35]],[[1,2,3,],[1432,142,344]]])
print(ary)
print("-"*18)
print(np.flip(ary,axis=0))#axis=1 dersen simetriyi farklı yerden alır
print("-"*18)
print(np.flipud(ary)),
print("-"*18)
print(ary.T) #satırlar sütun olur

[[[   1    2    3]
  [ 132  222   35]]

 [[   1    2    3]
  [1432  142  344]]]
------------------
[[[   1    2    3]
  [1432  142  344]]

 [[   1    2    3]
  [ 132  222   35]]]
------------------
[[[   1    2    3]
  [1432  142  344]]

 [[   1    2    3]
  [ 132  222   35]]]
------------------
[[[   1    1]
  [ 132 1432]]

 [[   2    2]
  [ 222  142]]

 [[   3    3]
  [  35  344]]]


In [33]:
ary2= np.array([[[1,2,3,],[132,222,35]],[[1,2,3,],[1432,142,344]]])
for a in np.nditer(ary2):
    print(a)

1
2
3
132
222
35
1
2
3
1432
142
344


In [35]:
ary2= np.array([[[1,2,3,],[132,222,35]],[[1,2,3,],[1432,142,344]]])  #türünü değiştirip alcaz
for a in np.nditer(ary2,flags=['buffered'],op_dtypes=['S']):
    print(a)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'132')
np.bytes_(b'222')
np.bytes_(b'35')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'1432')
np.bytes_(b'142')
np.bytes_(b'344')


In [39]:
ary2= np.array([[[0,2,3,],[132,222,35]],[[1,0,3,],[0,142,344]]])  #türünü değiştirip alcaz
for a in np.nditer(ary2,flags=['buffered'],op_dtypes=[np.bool_],casting='unsafe'): #veri kaybolur diye uyarı almayalım diye unsafe yaptık.
    print(a)

False
True
True
True
True
True
True
False
True
False
True
True


In [1]:
np.ndenumerate(ary)#Bu komut, dizinin içinde dolaşırken size sadece değeri değil, o değerin çok boyutlu dizideki indeksini (konumunu) de verir.

NameError: name 'np' is not defined